name: xcodebuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 14.1
      run: sudo xcode-select -s "/Applications/Xcode_14.1.app"
    - name: Build
      run: xcodebuild -verbose -configuration Debug
