name: push-and-prs-on-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Switch to Xcode 15.2
      run: sudo xcode-select -s "/Applications/Xcode_15.2.app"
    - name: Build
      run: xcodebuild -verbose -scheme MissingArt
