name: push-and-prs-on-main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v5
    - name: Switch to Xcode 16.0
      run: sudo xcode-select -s "/Applications/Xcode_16.0.app"
    - name: Build
      run: xcodebuild -verbose -scheme MissingArt
