name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Switch to Xcode 14.2
      run: sudo xcode-select -s "/Applications/Xcode_14.2.app"
    - name: Build
      run: xcodebuild -verbose -scheme MissingArt
