name: release-builds

on:
  release:
    branches: [ main ]
    types: [ published ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: Switch to Xcode 15.3
      run: sudo xcode-select -s "/Applications/Xcode_15.3.app"
    - name: Build
      run: xcodebuild -verbose -scheme MissingArt
